## Balance Sheet CSV

In [182]:
import pandas as pd

In [183]:
tracked_country_name_list = ["United Arab Emirates", "Austria", "Australia", "Belgium", "Canada", "Switzerland", "China", "Czech Republic", "Germany", "Denmark", "Egypt", "Spain", "Finland", "France", "United Kingdom", "Greece", "Hong Kong", "Hungary", "Indonesia", "Ireland", "Israel", "India", "Italy", "Jordan", "Korea", "Luxembourg", "Malaysia", "Netherlands", "Norway", "New Zealand", "Philippines", "Poland", "Portugal", "Qatar", "Russia", "Saudi Arabia", "Sweden", "Singapore", "Thailand", "Turkey", "Taiwan", "United States", "South Africa"]

In [184]:
bs_df = pd.read_excel('Valuation_data_cleaned.xlsx', sheet_name = 'Balance Sheet', header =24, nrows=44)

bs_global_intercept = bs_df.iloc[0,2]
# print(bs_global_intercept)

# remove global intercept row
bs_df = bs_df.iloc[1:, :]

# select only ISO and Coef column
bs_df = bs_df[["Variable", "Coef"]]

# rename column names to id and value to match js script
bs_df = bs_df.rename(columns={'Variable':"id", "Coef":"country coefficient"})

# df = df.set_index("id")
# df = df.set_index(range(df.shape[0]))
# df = df.reset_index()

# country scaling factor
bs_df["value"] = bs_df['country coefficient'] + bs_global_intercept

# round values to 4 decimal places
bs_df = bs_df.round({'country coefficient': 4, 'value': 4})

bs_df["name"] = tracked_country_name_list

# print(df.shape[0])
# print(len(tracked_country_name_list))

# rearrange order of columns
bs_df = bs_df[["id","name", "country coefficient", "value"]]
bs_df

    id                  name  country coefficient   value
1   AE  United Arab Emirates              -0.1044  0.8908
2   AT               Austria              -0.3397  0.6555
3   AU             Australia               0.1675  1.1627
4   BE               Belgium              -0.1358  0.8594
5   CA                Canada              -0.0561  0.9391
6   CH           Switzerland               0.1561  1.1513
7   CN                 China              -0.2565  0.7387
8   CZ        Czech Republic              -0.0553  0.9399
9   DE               Germany              -0.2235  0.7717
10  DK               Denmark               0.2275  1.2227
11  EG                 Egypt              -0.1966  0.7986
12  ES                 Spain              -0.0779  0.9173
13  FI               Finland               0.1382  1.1334
14  FR                France              -0.1838  0.8114
15  GB        United Kingdom              -0.1094  0.8858
16  GR                Greece              -0.2757  0.7195
17  HK             Hong Kong              -0.3366  0.6586
18  HU               Hungary              -0.0794  0.9158
19  ID             Indonesia               0.0663  1.0615
20  IE               Ireland               0.0607  1.0559
21  IL                Israel              -0.1240  0.8712
22  IN                 India               0.1349  1.1301
23  IT                 Italy              -0.3096  0.6856
24  JO                Jordan              -0.3614  0.6338
25  KR                 Korea              -0.4150  0.5802
26  LU            Luxembourg              -0.3135  0.6817
27  MY              Malaysia              -0.1579  0.8373
28  NL           Netherlands               0.0954  1.0906
29  NO                Norway              -0.0699  0.9253
30  NZ           New Zealand               0.1685  1.1637
31  PH           Philippines              -0.0561  0.9391
32  PL                Poland              -0.2842  0.7110
33  PT              Portugal              -0.0972  0.8980
34  QA                 Qatar               0.0273  1.0225
35  RU                Russia              -0.3415  0.6537
36  SA          Saudi Arabia               0.1517  1.1469
37  SE                Sweden               0.0567  1.0519
38  SG             Singapore              -0.2407  0.7545
39  TH              Thailand               0.0912  1.0864
40  TR                Turkey              -0.2520  0.7432
41  TW                Taiwan              -0.0651  0.9301
42  US         United States               0.2613  1.2565
43  ZA          South Africa              -0.0177  0.9775

In [185]:
bs_csv_file = bs_df.to_csv(r'balance_sheet.csv')

In [186]:

bs_df
# print(df.to_string())

for i in range(len(bs_df)):
    bs_string = "{ " + '''id: "{}", value: {}, "url": "../Compiled/Select_Industry/Select Industry_{}.html"'''.format(bs_df.iloc[i, 0], bs_df.iloc[i, 3], bs_df.iloc[i, 1]) + " },"
    print(bs_string)

{ id: "AE", value: 0.8908, "url": "../Compiled/Select_Industry/Select Industry_United Arab Emirates.html" },
{ id: "AT", value: 0.6555, "url": "../Compiled/Select_Industry/Select Industry_Austria.html" },
{ id: "AU", value: 1.1627, "url": "../Compiled/Select_Industry/Select Industry_Australia.html" },
{ id: "BE", value: 0.8594, "url": "../Compiled/Select_Industry/Select Industry_Belgium.html" },
{ id: "CA", value: 0.9391, "url": "../Compiled/Select_Industry/Select Industry_Canada.html" },
{ id: "CH", value: 1.1513, "url": "../Compiled/Select_Industry/Select Industry_Switzerland.html" },
{ id: "CN", value: 0.7387, "url": "../Compiled/Select_Industry/Select Industry_China.html" },
{ id: "CZ", value: 0.9399, "url": "../Compiled/Select_Industry/Select Industry_Czech Republic.html" },
{ id: "DE", value: 0.7717, "url": "../Compiled/Select_Industry/Select Industry_Germany.html" },
{ id: "DK", value: 1.2227, "url": "../Compiled/Select_Industry/Select Industry_Denmark.html" },
{ id: "EG", value: 0.7986, "url": "../Compiled/Select_Industry/Select Industry_Egypt.html" },
{ id: "ES", value: 0.9173, "url": "../Compiled/Select_Industry/Select Industry_Spain.html" },
{ id: "FI", value: 1.1334, "url": "../Compiled/Select_Industry/Select Industry_Finland.html" },
{ id: "FR", value: 0.8114, "url": "../Compiled/Select_Industry/Select Industry_France.html" },
{ id: "GB", value: 0.8858, "url": "../Compiled/Select_Industry/Select Industry_United Kingdom.html" },
{ id: "GR", value: 0.7195, "url": "../Compiled/Select_Industry/Select Industry_Greece.html" },
{ id: "HK", value: 0.6586, "url": "../Compiled/Select_Industry/Select Industry_Hong Kong.html" },
{ id: "HU", value: 0.9158, "url": "../Compiled/Select_Industry/Select Industry_Hungary.html" },
{ id: "ID", value: 1.0615, "url": "../Compiled/Select_Industry/Select Industry_Indonesia.html" },
{ id: "IE", value: 1.0559, "url": "../Compiled/Select_Industry/Select Industry_Ireland.html" },
{ id: "IL", value: 0.8712, "url": "../Compiled/Select_Industry/Select Industry_Israel.html" },
{ id: "IN", value: 1.1301, "url": "../Compiled/Select_Industry/Select Industry_India.html" },
{ id: "IT", value: 0.6856, "url": "../Compiled/Select_Industry/Select Industry_Italy.html" },
{ id: "JO", value: 0.6338, "url": "../Compiled/Select_Industry/Select Industry_Jordan.html" },
{ id: "KR", value: 0.5802, "url": "../Compiled/Select_Industry/Select Industry_Korea.html" },
{ id: "LU", value: 0.6817, "url": "../Compiled/Select_Industry/Select Industry_Luxembourg.html" },
{ id: "MY", value: 0.8373, "url": "../Compiled/Select_Industry/Select Industry_Malaysia.html" },
{ id: "NL", value: 1.0906, "url": "../Compiled/Select_Industry/Select Industry_Netherlands.html" },
{ id: "NO", value: 0.9253, "url": "../Compiled/Select_Industry/Select Industry_Norway.html" },
{ id: "NZ", value: 1.1637, "url": "../Compiled/Select_Industry/Select Industry_New Zealand.html" },
{ id: "PH", value: 0.9391, "url": "../Compiled/Select_Industry/Select Industry_Philippines.html" },
{ id: "PL", value: 0.711, "url": "../Compiled/Select_Industry/Select Industry_Poland.html" },
{ id: "PT", value: 0.898, "url": "../Compiled/Select_Industry/Select Industry_Portugal.html" },
{ id: "QA", value: 1.0225, "url": "../Compiled/Select_Industry/Select Industry_Qatar.html" },
{ id: "RU", value: 0.6537, "url": "../Compiled/Select_Industry/Select Industry_Russia.html" },
{ id: "SA", value: 1.1469, "url": "../Compiled/Select_Industry/Select Industry_Saudi Arabia.html" },
{ id: "SE", value: 1.0519, "url": "../Compiled/Select_Industry/Select Industry_Sweden.html" },
{ id: "SG", value: 0.7545, "url": "../Compiled/Select_Industry/Select Industry_Singapore.html" },
{ id: "TH", value: 1.0864, "url": "../Compiled/Select_Industry/Select Industry_Thailand.html" },
{ id: "TR", value: 0.7432, "url": "../Compiled/Select_Industry/Select Industry_Turkey.html" },
{ id: "TW", value: 0.9301, "url": "../Compiled/Select_Industry/Select Industry_Taiwan.html" },
{ id: "US", value: 1.2565, "url": "../Compiled/Select_Industry/Select Industry_United States.html" },
{ id: "ZA", value: 0.9775, "url": "../Compiled/Select_Industry/Select Industry_South Africa.html" },

## Income Statement CSV

In [187]:
is_df = pd.read_excel("Valuation_data_cleaned.xlsx", sheet_name = "Income Statement", header = 25, nrows = 44)

is_global_average = is_df.iloc[0,2]
# print(is_global_average)

# remove global intercept row
is_df = is_df[1:]

is_df = is_df[["Variable", "Coef"]]
is_df = is_df.rename(columns={"Variable":"id", "Coef":"country coefficient"})

is_df["name"] = tracked_country_name_list

is_df["value"] = is_df["country coefficient"] + is_global_average

is_df = is_df.round({"country coefficient": 4, "value": 4})

is_df = is_df[["id", "name", "country coefficient", "value"]]

is_df

    id                  name  country coefficient   value
1   AE  United Arab Emirates              -0.1839  0.8118
2   AT               Austria              -0.2630  0.7327
3   AU             Australia               0.1645  1.1602
4   BE               Belgium              -0.0788  0.9169
5   CA                Canada              -0.0167  0.9790
6   CH           Switzerland               0.2751  1.2708
7   CN                 China              -0.2960  0.6997
8   CZ        Czech Republic              -0.0593  0.9364
9   DE               Germany              -0.1706  0.8251
10  DK               Denmark               0.2316  1.2273
11  EG                 Egypt              -0.3039  0.6918
12  ES                 Spain              -0.1063  0.8894
13  FI               Finland               0.1499  1.1456
14  FR                France              -0.1484  0.8473
15  GB        United Kingdom              -0.0976  0.8981
16  GR                Greece              -0.1842  0.8115
17  HK             Hong Kong              -0.2657  0.7300
18  HU               Hungary              -0.1385  0.8572
19  ID             Indonesia               0.0143  1.0100
20  IE               Ireland               0.0680  1.0637
21  IL                Israel              -0.1109  0.8848
22  IN                 India               0.0475  1.0432
23  IT                 Italy              -0.2573  0.7384
24  JO                Jordan              -0.2994  0.6963
25  KR                 Korea              -0.3481  0.6476
26  LU            Luxembourg              -0.2060  0.7897
27  MY              Malaysia              -0.0566  0.9391
28  NL           Netherlands               0.1081  1.1038
29  NO                Norway              -0.0463  0.9494
30  NZ           New Zealand               0.2383  1.2340
31  PH           Philippines              -0.1080  0.8877
32  PL                Poland              -0.2363  0.7594
33  PT              Portugal              -0.0778  0.9179
34  QA                 Qatar               0.1258  1.1215
35  RU                Russia              -0.4474  0.5483
36  SA          Saudi Arabia               0.2777  1.2734
37  SE                Sweden               0.0832  1.0789
38  SG             Singapore              -0.1634  0.8323
39  TH              Thailand               0.0987  1.0944
40  TR                Turkey              -0.3534  0.6423
41  TW                Taiwan               0.0131  1.0088
42  US         United States               0.1726  1.1683
43  ZA          South Africa              -0.0807  0.9150

In [188]:
is_csv_file = is_df.to_csv(r'income_statement.csv')

In [189]:
is_df

for i in range(len(is_df)):
    is_string = "{ " + '''id: "{}", value: {}, "url": "../Compiled/Select_Industry/Select Industry_{}.html"'''.format(is_df.iloc[i, 0], is_df.iloc[i, 3], is_df.iloc[i, 1]) + " },"
    print(is_string)

{ id: "AE", value: 0.8118, "url": "../Compiled/Select_Industry/Select Industry_United Arab Emirates.html" },
{ id: "AT", value: 0.7327, "url": "../Compiled/Select_Industry/Select Industry_Austria.html" },
{ id: "AU", value: 1.1602, "url": "../Compiled/Select_Industry/Select Industry_Australia.html" },
{ id: "BE", value: 0.9169, "url": "../Compiled/Select_Industry/Select Industry_Belgium.html" },
{ id: "CA", value: 0.979, "url": "../Compiled/Select_Industry/Select Industry_Canada.html" },
{ id: "CH", value: 1.2708, "url": "../Compiled/Select_Industry/Select Industry_Switzerland.html" },
{ id: "CN", value: 0.6997, "url": "../Compiled/Select_Industry/Select Industry_China.html" },
{ id: "CZ", value: 0.9364, "url": "../Compiled/Select_Industry/Select Industry_Czech Republic.html" },
{ id: "DE", value: 0.8251, "url": "../Compiled/Select_Industry/Select Industry_Germany.html" },
{ id: "DK", value: 1.2273, "url": "../Compiled/Select_Industry/Select Industry_Denmark.html" },
{ id: "EG", value: 0.6918, "url": "../Compiled/Select_Industry/Select Industry_Egypt.html" },
{ id: "ES", value: 0.8894, "url": "../Compiled/Select_Industry/Select Industry_Spain.html" },
{ id: "FI", value: 1.1456, "url": "../Compiled/Select_Industry/Select Industry_Finland.html" },
{ id: "FR", value: 0.8473, "url": "../Compiled/Select_Industry/Select Industry_France.html" },
{ id: "GB", value: 0.8981, "url": "../Compiled/Select_Industry/Select Industry_United Kingdom.html" },
{ id: "GR", value: 0.8115, "url": "../Compiled/Select_Industry/Select Industry_Greece.html" },
{ id: "HK", value: 0.73, "url": "../Compiled/Select_Industry/Select Industry_Hong Kong.html" },
{ id: "HU", value: 0.8572, "url": "../Compiled/Select_Industry/Select Industry_Hungary.html" },
{ id: "ID", value: 1.01, "url": "../Compiled/Select_Industry/Select Industry_Indonesia.html" },
{ id: "IE", value: 1.0637, "url": "../Compiled/Select_Industry/Select Industry_Ireland.html" },
{ id: "IL", value: 0.8848, "url": "../Compiled/Select_Industry/Select Industry_Israel.html" },
{ id: "IN", value: 1.0432, "url": "../Compiled/Select_Industry/Select Industry_India.html" },
{ id: "IT", value: 0.7384, "url": "../Compiled/Select_Industry/Select Industry_Italy.html" },
{ id: "JO", value: 0.6963, "url": "../Compiled/Select_Industry/Select Industry_Jordan.html" },
{ id: "KR", value: 0.6476, "url": "../Compiled/Select_Industry/Select Industry_Korea.html" },
{ id: "LU", value: 0.7897, "url": "../Compiled/Select_Industry/Select Industry_Luxembourg.html" },
{ id: "MY", value: 0.9391, "url": "../Compiled/Select_Industry/Select Industry_Malaysia.html" },
{ id: "NL", value: 1.1038, "url": "../Compiled/Select_Industry/Select Industry_Netherlands.html" },
{ id: "NO", value: 0.9494, "url": "../Compiled/Select_Industry/Select Industry_Norway.html" },
{ id: "NZ", value: 1.234, "url": "../Compiled/Select_Industry/Select Industry_New Zealand.html" },
{ id: "PH", value: 0.8877, "url": "../Compiled/Select_Industry/Select Industry_Philippines.html" },
{ id: "PL", value: 0.7594, "url": "../Compiled/Select_Industry/Select Industry_Poland.html" },
{ id: "PT", value: 0.9179, "url": "../Compiled/Select_Industry/Select Industry_Portugal.html" },
{ id: "QA", value: 1.1215, "url": "../Compiled/Select_Industry/Select Industry_Qatar.html" },
{ id: "RU", value: 0.5483, "url": "../Compiled/Select_Industry/Select Industry_Russia.html" },
{ id: "SA", value: 1.2734, "url": "../Compiled/Select_Industry/Select Industry_Saudi Arabia.html" },
{ id: "SE", value: 1.0789, "url": "../Compiled/Select_Industry/Select Industry_Sweden.html" },
{ id: "SG", value: 0.8323, "url": "../Compiled/Select_Industry/Select Industry_Singapore.html" },
{ id: "TH", value: 1.0944, "url": "../Compiled/Select_Industry/Select Industry_Thailand.html" },
{ id: "TR", value: 0.6423, "url": "../Compiled/Select_Industry/Select Industry_Turkey.html" },
{ id: "TW", value: 1.0088, "url": "../Compiled/Select_Industry/Select Industry_Taiwan.html" },
{ id: "US", value: 1.1683, "url": "../Compiled/Select_Industry/Select Industry_United States.html" },
{ id: "ZA", value: 0.915, "url": "../Compiled/Select_Industry/Select Industry_South Africa.html" },

## Unique Revenue CSV

In [190]:
ur_df = pd.read_excel("Valuation_data_cleaned.xlsx", sheet_name = "Op Revenues", header = 25, nrows = 44)

ur_global_average = ur_df.iloc[0,2]
# print(ur_global_average)

ur_df = ur_df[1:]

ur_df = ur_df[["Variable", "Coef"]]
ur_df = ur_df.rename(columns = {"Variable":"id", "Coef":"country coefficient"})

ur_df["name"] = tracked_country_name_list

ur_df["value"] = ur_df["country coefficient"] + ur_global_average

ur_df = ur_df.round({"value" : 4, "country coefficient" : 4})

ur_df = ur_df[["id", "name", "country coefficient", "value"]]

ur_df

    id                  name  country coefficient   value
1   AE  United Arab Emirates              -0.2418  0.7562
2   AT               Austria               0.1354  1.1334
3   AU             Australia               0.1780  1.1760
4   BE               Belgium              -0.0874  0.9106
5   CA                Canada              -0.1224  0.8756
6   CH           Switzerland              -0.0079  0.9901
7   CN                 China              -0.0885  0.9095
8   CZ        Czech Republic              -0.0528  0.9452
9   DE               Germany               0.1290  1.1270
10  DK               Denmark               0.1332  1.1312
11  EG                 Egypt               0.1903  1.1883
12  ES                 Spain               0.0645  1.0625
13  FI               Finland               0.1187  1.1167
14  FR                France              -0.0867  0.9113
15  GB        United Kingdom               0.0081  1.0061
16  GR                Greece              -0.0797  0.9183
17  HK             Hong Kong              -0.2161  0.7819
18  HU               Hungary               0.1255  1.1235
19  ID             Indonesia              -0.0453  0.9527
20  IE               Ireland               0.0672  1.0652
21  IL                Israel              -0.3814  0.6166
22  IN                 India               0.0558  1.0538
23  IT                 Italy              -0.1384  0.8596
24  JO                Jordan              -0.4266  0.5714
25  KR                 Korea              -0.0371  0.9609
26  LU            Luxembourg              -0.0807  0.9173
27  MY              Malaysia              -0.2273  0.7707
28  NL           Netherlands              -0.0705  0.9275
29  NO                Norway              -0.2133  0.7847
30  NZ           New Zealand               0.0265  1.0245
31  PH           Philippines              -0.1648  0.8332
32  PL                Poland              -0.0061  0.9919
33  PT              Portugal              -0.0458  0.9522
34  QA                 Qatar              -0.3668  0.6312
35  RU                Russia              -0.1173  0.8807
36  SA          Saudi Arabia              -0.5827  0.4153
37  SE                Sweden               0.0533  1.0513
38  SG             Singapore              -0.1175  0.8805
39  TH              Thailand               0.0107  1.0087
40  TR                Turkey               0.0782  1.0762
41  TW                Taiwan              -0.0437  0.9543
42  US         United States              -0.0081  0.9899
43  ZA          South Africa               0.0024  1.0004

In [191]:
ur_csv_file = ur_df.to_csv(r'op_revenue.csv')

In [198]:
ur_df

for i in range(len(ur_df)):
    ur_string = "{ " + '''id: "{}", value: {}, "url": "../Compiled/Select_Industry/Select Industry_{}.html"'''.format(ur_df.iloc[i, 0], ur_df.iloc[i, 3], ur_df.iloc[i, 1]) + " },"
    print(ur_string)

{ id: "AE", value: 0.7562, "url": "../Compiled/Select_Industry/Select Industry_United Arab Emirates.html" },
{ id: "AT", value: 1.1334, "url": "../Compiled/Select_Industry/Select Industry_Austria.html" },
{ id: "AU", value: 1.176, "url": "../Compiled/Select_Industry/Select Industry_Australia.html" },
{ id: "BE", value: 0.9106, "url": "../Compiled/Select_Industry/Select Industry_Belgium.html" },
{ id: "CA", value: 0.8756, "url": "../Compiled/Select_Industry/Select Industry_Canada.html" },
{ id: "CH", value: 0.9901, "url": "../Compiled/Select_Industry/Select Industry_Switzerland.html" },
{ id: "CN", value: 0.9095, "url": "../Compiled/Select_Industry/Select Industry_China.html" },
{ id: "CZ", value: 0.9452, "url": "../Compiled/Select_Industry/Select Industry_Czech Republic.html" },
{ id: "DE", value: 1.127, "url": "../Compiled/Select_Industry/Select Industry_Germany.html" },
{ id: "DK", value: 1.1312, "url": "../Compiled/Select_Industry/Select Industry_Denmark.html" },
{ id: "EG", value: 1.1883, "url": "../Compiled/Select_Industry/Select Industry_Egypt.html" },
{ id: "ES", value: 1.0625, "url": "../Compiled/Select_Industry/Select Industry_Spain.html" },
{ id: "FI", value: 1.1167, "url": "../Compiled/Select_Industry/Select Industry_Finland.html" },
{ id: "FR", value: 0.9113, "url": "../Compiled/Select_Industry/Select Industry_France.html" },
{ id: "GB", value: 1.0061, "url": "../Compiled/Select_Industry/Select Industry_United Kingdom.html" },
{ id: "GR", value: 0.9183, "url": "../Compiled/Select_Industry/Select Industry_Greece.html" },
{ id: "HK", value: 0.7819, "url": "../Compiled/Select_Industry/Select Industry_Hong Kong.html" },
{ id: "HU", value: 1.1235, "url": "../Compiled/Select_Industry/Select Industry_Hungary.html" },
{ id: "ID", value: 0.9527, "url": "../Compiled/Select_Industry/Select Industry_Indonesia.html" },
{ id: "IE", value: 1.0652, "url": "../Compiled/Select_Industry/Select Industry_Ireland.html" },
{ id: "IL", value: 0.6166, "url": "../Compiled/Select_Industry/Select Industry_Israel.html" },
{ id: "IN", value: 1.0538, "url": "../Compiled/Select_Industry/Select Industry_India.html" },
{ id: "IT", value: 0.8596, "url": "../Compiled/Select_Industry/Select Industry_Italy.html" },
{ id: "JO", value: 0.5714, "url": "../Compiled/Select_Industry/Select Industry_Jordan.html" },
{ id: "KR", value: 0.9609, "url": "../Compiled/Select_Industry/Select Industry_Korea.html" },
{ id: "LU", value: 0.9173, "url": "../Compiled/Select_Industry/Select Industry_Luxembourg.html" },
{ id: "MY", value: 0.7707, "url": "../Compiled/Select_Industry/Select Industry_Malaysia.html" },
{ id: "NL", value: 0.9275, "url": "../Compiled/Select_Industry/Select Industry_Netherlands.html" },
{ id: "NO", value: 0.7847, "url": "../Compiled/Select_Industry/Select Industry_Norway.html" },
{ id: "NZ", value: 1.0245, "url": "../Compiled/Select_Industry/Select Industry_New Zealand.html" },
{ id: "PH", value: 0.8332, "url": "../Compiled/Select_Industry/Select Industry_Philippines.html" },
{ id: "PL", value: 0.9919, "url": "../Compiled/Select_Industry/Select Industry_Poland.html" },
{ id: "PT", value: 0.9522, "url": "../Compiled/Select_Industry/Select Industry_Portugal.html" },
{ id: "QA", value: 0.6312, "url": "../Compiled/Select_Industry/Select Industry_Qatar.html" },
{ id: "RU", value: 0.8807, "url": "../Compiled/Select_Industry/Select Industry_Russia.html" },
{ id: "SA", value: 0.4153, "url": "../Compiled/Select_Industry/Select Industry_Saudi Arabia.html" },
{ id: "SE", value: 1.0513, "url": "../Compiled/Select_Industry/Select Industry_Sweden.html" },
{ id: "SG", value: 0.8805, "url": "../Compiled/Select_Industry/Select Industry_Singapore.html" },
{ id: "TH", value: 1.0087, "url": "../Compiled/Select_Industry/Select Industry_Thailand.html" },
{ id: "TR", value: 1.0762, "url": "../Compiled/Select_Industry/Select Industry_Turkey.html" },
{ id: "TW", value: 0.9543, "url": "../Compiled/Select_Industry/Select Industry_Taiwan.html" },
{ id: "US", value: 0.9899, "url": "../Compiled/Select_Industry/Select Industry_United States.html" },
{ id: "ZA", value: 1.0004, "url": "../Compiled/Select_Industry/Select Industry_South Africa.html" },

## Unique Earnings CSV

In [196]:
ue_df = pd.read_excel("Valuation_data_cleaned.xlsx", sheet_name = "Op Earnings", header = 25, nrows = 44)

ue_global_average = ue_df.iloc[0,2]
# print(ue_global_average)

ue_df = ue_df[1:]
ue_df = ue_df[["Variable", "Coef"]]
ue_df = ue_df.rename(columns = {"Variable":"id", "Coef":"country coefficient"})

ue_df["name"] = tracked_country_name_list

ue_df["value"] = ue_df["country coefficient"] + ue_global_average

ue_df = ue_df.round({"country coefficient" : 4, "value" : 4})
ue_df = ue_df[["id", "name", "country coefficient", "value"]]

ue_df

    id                  name  country coefficient   value
1   AE  United Arab Emirates               0.1332  1.1332
2   AT               Austria              -0.1811  0.8189
3   AU             Australia               0.0339  1.0339
4   BE               Belgium              -0.0649  0.9351
5   CA                Canada              -0.0580  0.9420
6   CH           Switzerland              -0.1279  0.8721
7   CN                 China              -0.0712  0.9288
8   CZ        Czech Republic               0.3759  1.3759
9   DE               Germany               0.0694  1.0694
10  DK               Denmark               0.1537  1.1537
11  EG                 Egypt               0.1159  1.1159
12  ES                 Spain               0.0088  1.0088
13  FI               Finland              -0.0523  0.9477
14  FR                France              -0.0450  0.9550
15  GB        United Kingdom               0.0862  1.0862
16  GR                Greece              -0.1154  0.8846
17  HK             Hong Kong              -0.2404  0.7596
18  HU               Hungary               0.2553  1.2553
19  ID             Indonesia               0.1211  1.1211
20  IE               Ireland               0.0622  1.0622
21  IL                Israel               0.2033  1.2033
22  IN                 India              -0.0628  0.9372
23  IT                 Italy               0.0300  1.0300
24  JO                Jordan              -0.0942  0.9058
25  KR                 Korea              -0.1500  0.8500
26  LU            Luxembourg               0.0086  1.0086
27  MY              Malaysia              -0.2926  0.7074
28  NL           Netherlands               0.0752  1.0752
29  NO                Norway               0.2509  1.2509
30  NZ           New Zealand               0.0207  1.0207
31  PH           Philippines               0.0246  1.0246
32  PL                Poland               0.0196  1.0196
33  PT              Portugal               0.1710  1.1710
34  QA                 Qatar              -0.1066  0.8934
35  RU                Russia               0.5081  1.5081
36  SA          Saudi Arabia              -0.0928  0.9072
37  SE                Sweden              -0.0774  0.9226
38  SG             Singapore              -0.2387  0.7613
39  TH              Thailand              -0.0799  0.9201
40  TR                Turkey               0.1552  1.1552
41  TW                Taiwan              -0.3143  0.6857
42  US         United States               0.2200  1.2200
43  ZA          South Africa               0.0969  1.0969

In [197]:
ue_csv_file = ue_df.to_csv(r'op_earnings.csv')

In [199]:
ue_df

for i in range(len(ue_df)):
    ue_string = "{ " + '''id: "{}", value: {}, "url": "../Compiled/Select_Industry/Select Industry_{}.html"'''.format(ue_df.iloc[i, 0], ue_df.iloc[i, 3], ue_df.iloc[i, 1]) + " },"
    print(ue_string)

{ id: "AE", value: 1.1332, "url": "../Compiled/Select_Industry/Select Industry_United Arab Emirates.html" },
{ id: "AT", value: 0.8189, "url": "../Compiled/Select_Industry/Select Industry_Austria.html" },
{ id: "AU", value: 1.0339, "url": "../Compiled/Select_Industry/Select Industry_Australia.html" },
{ id: "BE", value: 0.9351, "url": "../Compiled/Select_Industry/Select Industry_Belgium.html" },
{ id: "CA", value: 0.942, "url": "../Compiled/Select_Industry/Select Industry_Canada.html" },
{ id: "CH", value: 0.8721, "url": "../Compiled/Select_Industry/Select Industry_Switzerland.html" },
{ id: "CN", value: 0.9288, "url": "../Compiled/Select_Industry/Select Industry_China.html" },
{ id: "CZ", value: 1.3759, "url": "../Compiled/Select_Industry/Select Industry_Czech Republic.html" },
{ id: "DE", value: 1.0694, "url": "../Compiled/Select_Industry/Select Industry_Germany.html" },
{ id: "DK", value: 1.1537, "url": "../Compiled/Select_Industry/Select Industry_Denmark.html" },
{ id: "EG", value: 1.1159, "url": "../Compiled/Select_Industry/Select Industry_Egypt.html" },
{ id: "ES", value: 1.0088, "url": "../Compiled/Select_Industry/Select Industry_Spain.html" },
{ id: "FI", value: 0.9477, "url": "../Compiled/Select_Industry/Select Industry_Finland.html" },
{ id: "FR", value: 0.955, "url": "../Compiled/Select_Industry/Select Industry_France.html" },
{ id: "GB", value: 1.0862, "url": "../Compiled/Select_Industry/Select Industry_United Kingdom.html" },
{ id: "GR", value: 0.8846, "url": "../Compiled/Select_Industry/Select Industry_Greece.html" },
{ id: "HK", value: 0.7596, "url": "../Compiled/Select_Industry/Select Industry_Hong Kong.html" },
{ id: "HU", value: 1.2553, "url": "../Compiled/Select_Industry/Select Industry_Hungary.html" },
{ id: "ID", value: 1.1211, "url": "../Compiled/Select_Industry/Select Industry_Indonesia.html" },
{ id: "IE", value: 1.0622, "url": "../Compiled/Select_Industry/Select Industry_Ireland.html" },
{ id: "IL", value: 1.2033, "url": "../Compiled/Select_Industry/Select Industry_Israel.html" },
{ id: "IN", value: 0.9372, "url": "../Compiled/Select_Industry/Select Industry_India.html" },
{ id: "IT", value: 1.03, "url": "../Compiled/Select_Industry/Select Industry_Italy.html" },
{ id: "JO", value: 0.9058, "url": "../Compiled/Select_Industry/Select Industry_Jordan.html" },
{ id: "KR", value: 0.85, "url": "../Compiled/Select_Industry/Select Industry_Korea.html" },
{ id: "LU", value: 1.0086, "url": "../Compiled/Select_Industry/Select Industry_Luxembourg.html" },
{ id: "MY", value: 0.7074, "url": "../Compiled/Select_Industry/Select Industry_Malaysia.html" },
{ id: "NL", value: 1.0752, "url": "../Compiled/Select_Industry/Select Industry_Netherlands.html" },
{ id: "NO", value: 1.2509, "url": "../Compiled/Select_Industry/Select Industry_Norway.html" },
{ id: "NZ", value: 1.0207, "url": "../Compiled/Select_Industry/Select Industry_New Zealand.html" },
{ id: "PH", value: 1.0246, "url": "../Compiled/Select_Industry/Select Industry_Philippines.html" },
{ id: "PL", value: 1.0196, "url": "../Compiled/Select_Industry/Select Industry_Poland.html" },
{ id: "PT", value: 1.171, "url": "../Compiled/Select_Industry/Select Industry_Portugal.html" },
{ id: "QA", value: 0.8934, "url": "../Compiled/Select_Industry/Select Industry_Qatar.html" },
{ id: "RU", value: 1.5081, "url": "../Compiled/Select_Industry/Select Industry_Russia.html" },
{ id: "SA", value: 0.9072, "url": "../Compiled/Select_Industry/Select Industry_Saudi Arabia.html" },
{ id: "SE", value: 0.9226, "url": "../Compiled/Select_Industry/Select Industry_Sweden.html" },
{ id: "SG", value: 0.7613, "url": "../Compiled/Select_Industry/Select Industry_Singapore.html" },
{ id: "TH", value: 0.9201, "url": "../Compiled/Select_Industry/Select Industry_Thailand.html" },
{ id: "TR", value: 1.1552, "url": "../Compiled/Select_Industry/Select Industry_Turkey.html" },
{ id: "TW", value: 0.6857, "url": "../Compiled/Select_Industry/Select Industry_Taiwan.html" },
{ id: "US", value: 1.22, "url": "../Compiled/Select_Industry/Select Industry_United States.html" },
{ id: "ZA", value: 1.0969, "url": "../Compiled/Select_Industry/Select Industry_South Africa.html" },